setup:
    resource: "@SetupBundle/Controller/"
    type:     annotation
    prefix:   /install

app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_extra:
    resource: '@AppBundle/Resources/config/routing/routing.yml'

